title: iMOPSE
description: Documentation for the iMOPSE project.
remote_theme: just-the-docs/just-the-docs

# Enable Jekyll to look for Markdown files in 'docs' folder
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Navigation
just_the_docs:
  navigation:
    - title: "Home"
      url: "/"
    - title: "Compile Project"
      url: "/docs/compile_project/"
    - title: "Optimizer"
      url: "/docs/optimizer/"
    - title: "Pareto Analyzer"
      url: "/docs/pareto_analyzer/"
    - title: "Additional Tools"
      url: "/docs/additional_tools/"
    - title: "Methods"
      url: "/docs/methods/"
    - title: "Problems"
      url: "/docs/problems/"
    - title: "Example of Use"
      url: "/docs/example_of_use/"
    - title: "Support"
      url: "/docs/support/"
    - title: "Authors and Acknowledgment"
      url: "/docs/authors/"
    - title: "Contributors"
      url: "/docs/contributors/"