title: iMOPSE
description: Documentation
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

color_scheme: light

collections:
  docs:
    output: true
    permalink: /:collection/:path/